version: "3.8"
services:
  api:
    # image: test/dockerised
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment: 
      DATABASE_URL: postgresql://postgres:F4dS12x87@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports: 
      - "8080:3000"
  
  postgres:
    image: postgres:13.1
    ports: 
      - "35000:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F4dS12x87
      POSTGRES_DB: db

